ecommerce/checkout/urls.py
from django.urls import path 
from . views import checkout,charge, oderView, OrderList, CartView

app_name = "checkout"

urlpatterns = [
	path('checkout/', checkout, name="index"),
	path('charge/', charge, name="charge"),
	path('my-orders/', oderView, name="oderView"),
	path('listado_pedido', OrderList.as_view(), name="orderlist"),
	path('pedido/<username>',CartView, name='order_listar'),    
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
 	path('', include('products.urls')),
 	path('', include('checkout.urls',)),
    path('admin/', admin.site.urls),
    path('accounts/', include('registration.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/products/urls.py
from django.urls import path, re_path
from cart.views import add_to_cart, remove_from_cart, CartView, decreaseCart
from .views import Home, home1,  ProductDetail, Productos, SingleCat

app_name="mainapp"
urlpatterns = [
    path('inicio', Home.as_view(), name='home'),
    path('', home1, name='inicio'),
    path('product/<slug>/', ProductDetail.as_view(), name='product'),
    path('cart/', CartView, name='cart-home'),
    path('cart/<slug>', add_to_cart, name='cart'),
    path('decrease-cart/<slug>', decreaseCart, name='decrease-cart'),
    path('remove/<slug>', remove_from_cart, name='remove-cart'),
    re_path(r'^(?P<pk>\d+)$', SingleCat.as_view(), name='category_details'),
]	

ecommerce/cart/models.py
from django.db import models
from django.contrib.auth import get_user_model
from products.models import Product

# Get the user model
User = get_user_model()


# Cart Model
class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    purchased = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f'{self.quantity} de {self.item.name}'

    def get_total(self):
        total = self.item.price * self.quantity
        floattotal = float("{0:.2f}".format(total))
        return floattotal

# Order Model
class Order(models.Model):
    orderitems  = models.ManyToManyField(Cart)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    encargado = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    comentarios = models.CharField(max_length=200, blank=True , null=True)
    orderId = models.CharField(max_length=200, blank=True, null=True)
    
    def __str__(self):
        return self.user.email

    class Meta:
        ordering = ["user"]
        verbose_name = ("Pedido")
        verbose_name_plural = ("Pedidos")


    def get_totals(self):
        total = 0
        for order_item in self.orderitems.all():
            total += order_item.get_total()
        
        return total

ecommerce/cart/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView
from .models import Cart, Order
from products.models import Product



# Add to Cart View

def add_to_cart(request, slug):
    item = get_object_or_404(Product, slug=slug)
    order_item, created = Cart.objects.get_or_create(
        item=item,
        user=request.user
    )
    order_qs = Order.objects.filter(user=request.user, encargado=False)
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.orderitems.filter(item__slug=item.slug).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, f"{item.name} Cantidad Actualizada.")
            return redirect("mainapp:cart-home")
        else:
            order.orderitems.add(order_item)
            messages.info(request, f"{item.name} Ha sido agregado a su pedido.")
            return redirect("mainapp:cart-home")
    else:
        order = Order.objects.create(
            user=request.user)
        order.orderitems.add(order_item)
        messages.info(request, f"{item.name} Ha sido agregado a su pedido.")
        return redirect("mainapp:cart-home")




# Remove item from cart

def remove_from_cart(request, slug):
    item = get_object_or_404(Product, slug=slug)
    cart_qs = Cart.objects.filter(user=request.user, item=item)
    if cart_qs.exists():
        cart = cart_qs[0]
        # Checking the cart quantity
        if cart.quantity > 1:
            cart.quantity -= 1
            cart.save()
        else:
            cart_qs.delete()
    order_qs = Order.objects.filter(
        user=request.user,
        encargado=False
    )
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.orderitems.filter(item__slug=item.slug).exists():
            order_item = Cart.objects.filter(
                item=item,
                user=request.user,
            )[0]
            order.orderitems.remove(order_item)
            messages.warning(request, "Este artículo ha sido eliminado de su pedido.")
            return redirect("mainapp:home")
        else:
            messages.warning(request, "Este artículo no se encuentra en su pedido")
            return redirect("mainapp:home")
    else:
        messages.warning(request, "No tienes un pedido realizado.")
        return redirect("mainapp:home")


# Cart View

def CartView(request):

    user = request.user

    carts = Cart.objects.filter(user=user, purchased=False)
    orders = Order.objects.filter(user=user, encargado=False)

    if carts.exists():
        if orders.exists():
            order = orders[0]
            return render(request, 'cart/home.html', {"carts": carts, 'order': order})
        else:
            messages.warning(request, "No tienes productos agregados en tu pedido")
            return redirect("mainapp:home")
		
    else:
        messages.warning(request, "No tienes productos agregados en tu pedido")
        return redirect("mainapp:home")



# Decrease the quantity of the cart :

def decreaseCart(request, slug):
    item = get_object_or_404(Product, slug=slug)
    order_qs = Order.objects.filter(
        user=request.user,
        encargado=False
    )
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.orderitems.filter(item__slug=item.slug).exists():
            order_item = Cart.objects.filter(
                item=item,
                user=request.user
            )[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
            else:
                order.orderitems.remove(order_item)
                order_item.delete()
                messages.warning(request, f"{item.name} Ha sido eliminado de tu pedido.")
            messages.info(request, f"{item.name} Cantidad actualizada.")
            return redirect("mainapp:cart-home")
        else:
            messages.info(request, f"{item.name} Cantidad actualizada.")
            return redirect("mainapp:cart-home")
    else:
        messages.info(request, "No tienen un pedido realizado")
        return redirect("mainapp:cart-home")

ecommerce/cart/templates/cart/home.html
{% extends 'products/base.html' %}
{% load static %}
{% block title %}Inicio{% endblock %}
{% block header %}
    <header id="carrito">
    <div class="menu">
      <div class="contenedor">
        <div id="introduccion">
          <p class="blanco"><span>Venta Oficial</span> de la marca Saphirus®</p>
          <p class="blanco">Aromatización ambiental</p>
          <p class="blanco">Contamos con toda la linea de productos.</p>
        </div>
        <div id="imagen">
          <a href= "{% url 'mainapp:inicio' %}"><img id="logo-login" src={% static "products/imagenes/logo.jpeg" %}></a>
        </div>
        <div>
          <img id="saphirus" src= {% static 'products/imagenes/saphirus.jpeg' %}>
        </div>
      </div>
    </div>

{% block content %}
<div class="container" id="carrito10">
<div>
	<h2 class="blanco catalogo">Historial de Artículos</h2>
</div>
<table class="table table-hover pedido">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Producto</th>
      <th scope="col">Cantidad</th>
      <th scope="col">Precio</th>
    </tr>
  </thead>
  <tbody>
  	{% for cart in carts %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ cart.item.name }}</td>
      <td>
        <a class="mr-2" href="{% url 'mainapp:decrease-cart' cart.item.slug %}"><span class="badge badge-light"><i class="fas fa-minus"></i></span></a>
      {{ cart.quantity }}
      <a class="ml-2" href="{% url 'mainapp:cart' cart.item.slug %}" ><span class="badge badge-light"><i class="fas fa-plus"></i></span></a>
      </td>
      <td>${{ cart.get_total }}</td>
    </tr>
	{% endfor %}
    <tr>
      <th scope="row"></th>
      <td colspan="2">Total</td>
      <td>${{ order.get_totals| floatformat:2 }}</td>
    </tr>
    <tr>
      <th scope="row"></th>
      <td colspan="3" >
        <a href="{% url 'mainapp:home' %}" class="btn btn-warning mr-4 continuar" >Continuar comprando</a>
        <a href="{% url 'checkout:index' %}" class="btn btn-success mr-4 continuar">Finalizar pedido</a>
      </td>
    </tr>
  </tbody>
</table>
</div>

{% endblock %}
</header>
{% endblock %}
{% block footer %}

  <footer id="footercarrito">
  <div class="contenedor">
    <ul>
      <li>
        <img class="login-img" src= {% static "products/imagenes/user.png" %}>
        <h3 class="login">Atención Personalizada</h3>
      </li>
      <li>
        <img class="login-img" src= {% static "products/imagenes/carrito.png" %}>
        <h3 class="login">Pedidos Online</h3>
      </li>
      <li>
        <img class="login-img" id="ubicacion" src= {% static "products/imagenes/map.png" %}>
        <h3 class="login">Envíos a todo el país</h3>
      </li>
      <li>
        <img class="login-img" src= {% static "products/imagenes/candado.png" %}>
        <h3 class="login">Plataforma de pago seguro</h3>
      </li>
    </ul>
  </div>
</footer>

{% endblock %}