ecommerce/checkout/urls.py
from django.urls import path 
from . views import checkout,charge, oderView, OrderList, CartView

app_name = "checkout"

urlpatterns = [
	path('checkout/', checkout, name="index"),
	path('charge/', charge, name="charge"),
	path('my-orders/', oderView, name="oderView"),
	path('listado_pedido', OrderList.as_view(), name="orderlist"),
	path('pedido/<username>',CartView, name='order_listar'),    
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
 	path('', include('products.urls')),
 	path('', include('checkout.urls',)),
    path('admin/', admin.site.urls),
    path('accounts/', include('registration.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/products/urls.py
from django.urls import path, re_path
from cart.views import add_to_cart, remove_from_cart, CartView, decreaseCart
from .views import Home, home1,  ProductDetail, Productos, SingleCat

app_name="mainapp"
urlpatterns = [
    path('inicio', Home.as_view(), name='home'),
    path('', home1, name='inicio'),
    path('product/<slug>/', ProductDetail.as_view(), name='product'),
    path('cart/', CartView, name='cart-home'),
    path('cart/<slug>', add_to_cart, name='cart'),
    path('decrease-cart/<slug>', decreaseCart, name='decrease-cart'),
    path('remove/<slug>', remove_from_cart, name='remove-cart'),
    re_path(r'^(?P<pk>\d+)$', SingleCat.as_view(), name='category_details'),
]	

ecommerce/products/models.py
from django.db import models
from django.urls import reverse
from django_extensions.db.fields import AutoSlugField

# Category Model
class Category(models.Model):
    title = models.CharField(max_length=300)
    slug = AutoSlugField(populate_from=['title'])

   
    class Meta:
        ordering = ["title"]
        verbose_name = ("Categoria")
        verbose_name_plural = ("Categorias")

    def __str__(self):
        return self.title
    


#Product Model
class  Product(models.Model):
    name = models.CharField(max_length=300)
    slug = AutoSlugField(populate_from=['name'])
    categories = models.ForeignKey(Category, blank=True, on_delete=models.CASCADE)
    preview_text = models.TextField(max_length=200, verbose_name='Preview Text')
    detail_text = models.TextField(max_length=1000, verbose_name='Detail Text')
    price = models.FloatField()
    

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]
        verbose_name = ("Producto")
        verbose_name_plural = ("Productos")


    def get_absolute_url(self):
        return reverse("mainapp:product", kwargs={
            'slug': self.slug
        })

ecommerce/products/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from products.models import Product, Category
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, render_to_response
from django.core.paginator import Paginator

class Home(ListView):
    model = Category
    template_name = 'products/home.html'

    

class Productos(ListView):
    model = Product
    template_name = 'products/home2.html'


class ProductDetail(LoginRequiredMixin, DetailView):
	model = Product

def home1(request):
    return render(request, "products/base2.html")

    
class SingleCat(DetailView):
    model = Category
    

    def get_context_data(self, **kwargs):
       context = super().get_context_data(**kwargs)
       current_category = context['object']
       context['products'] = current_category.product_set.all()
       return context

ecommerce/products/templates/products/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'products/estilos/estilo_propio.css' %}">
  <title> {% block title %}GLUSH AROMAS{% endblock %} | Florencia Sosa</title>
  <link href="https://fonts.googleapis.com/css?family=Rubik&display=swap" rel="stylesheet"> 
  <link href="https://fonts.googleapis.com/css?family=Oswald&display=swap" rel="stylesheet">

  <style>
  	.card{
  		    height: 350px;
  	}
  	.card-product:after {
    content: "";
    display: table;
    clear: both;
    visibility: hidden; }
  .card-product .price-new, .card-product .price {
    margin-right: 5px; }
  .card-product .price-old {
    color: #999; }
  .card-product .img-wrap {
    border-radius: 3px 3px 0 0;
    overflow: hidden;
    position: relative;
    height: 220px;
    text-align: center; }
    .card-product .img-wrap img {
      max-height: 100%;
      max-width: 100%;
      object-fit: cover; }
      
      .card-product .info-wrap {
    overflow: hidden;
    padding: 15px;
    border-top: 1px solid #eee; }
  .card-product .action-wrap {
    padding-top: 4px;
    margin-top: 4px; }
  .card-product .bottom-wrap {
    padding: 15px;
    border-top: 1px solid #eee; }
  .card-product .title {
    margin-top: 0; }
  </style>
</head>
<body>
  {% block header %}
  
    {% if messages %}
    <div class="messages container mt-2">
        {% for message in messages %}
        <div {% if message.tags %} class="alert alert-{{ message.tags }}{% endif %}" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
        </div>
        {% endfor %}
    </div>
  {% endif %}
{% block content %}
{% endblock %}
{% endblock %}
{% block footer %}
{% endblock %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<script>
  
</script>
</body>
</html>

ecommerce/products/templates/products/base2.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta name="viewport" content="width=device-width, user-scalable=no">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
  	<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'products/estilos/estilo_propio.css' %}">
	<link href="https://unpkg.com/ionicons@4.5.10-0/dist/css/ionicons.min.css" rel="stylesheet">
	<meta charset="utf-8">
	<title>GLUSH AROMAS | Florencia Sosa </title>
</head>


<body>

	<header>
		<div class="menu">
			<div class="contenedor">
				<div id="introduccion">
					<p class="blanco"><span>Venta Oficial</span> de la marca Saphirus®</p>
					<p class="blanco">Aromatización ambiental</p>
					<p class="blanco">Contamos con toda la linea de productos.</p>
				</div>
				<div class="carro">
				    <img id="carroinicio" src= {% static "products/imagenes/carrito.png" %}>
				    <p id="tiendaonline">TIENDA ONLINE</p>
				</div>
				<div>
					<img id="saphirus" src= {% static 'products/imagenes/saphirus.jpeg' %}>
				</div>
			</div>

		</div>

		<div class="contenedor-principal">
			<div class="contenedor-izquierda">
				<div class="contenedor-titulo-izquierda">
					<p class="blanco">PEDÍ CATÁLOGO</p>
					<p class="blanco">DIGITAL AHORA!</p>
					<p class="blanco"><span id=telefono>1124675666</span></p>
					<a id="whatsapp" href="https://api.whatsapp.com/send?phone=5491124675666"><img id="whatsapp" src={% static "products/imagenes/whatsapp.png" %}></a>
				</div>
				<div>
					<img id="saphirus2" src= {% static "products/imagenes/saphirus2.png" %}>
				</div>
			</div>
			<div class="contenedor-derecha">
				<div class="contenedor-titulo">
					<a class="link-inicio" href="{% url 'signup' %}">REGISTRARSE</a>
					<p class="blanco" id="cliente">Si ya sos cliente</p>
					{% if not request.user.is_authenticated %}
					<a class="link-inicio" href="{% url 'login' %}">INICIAR SESIÓN</a>
					{% else %}
					{% if request.user.is_staff %}
					<a class="link-inicio" href="{% url 'checkout:orderlist' %}">VER PEDIDOS</a>
					{% else %}
					<a class="link-inicio" href="{% url 'mainapp:home' %}">REALIZAR PEDIDO</a>
					<a class="link-inicio" href="{% url 'logout' %}">CERRAR SESIÓN</a>
					{% endif %}
					{% endif %}
				</div>
				<div id="imagen">
					<img id="logo" src={% static "products/imagenes/logo.jpeg" %}>
				</div>
				<div class="contacto">
					<h3 class="blanco">Contacto:</h3>
					<div class="redes">
						<img id="face" src= {% static "products/imagenes/facebook.png" %}>
						<img id="ing" src= {% static "products/imagenes/ing.png" %}>
						<img id="wp"src= {% static "products/imagenes/whatsapp.png" %}>
						<p class="blanco" id="telefono">1124675666</p>
					</div>
				</div>
			</div>
		</div>
	</header>
	<footer>
		<div class="contenedor">
			<ul>
				<li>
					<img src= {% static "products/imagenes/user.png" %}>
					<h3>Atención Personalizada</h3>
				</li>
				<li>
					<img src= {% static "products/imagenes/carrito.png" %}>
					<h3>Pedidos Online</h3>
				</li>
				<li>
					<img id="ubicacion" src= {% static "products/imagenes/map.png" %}>
					<h3>Envíos a todo el país</h3>
				</li>
				<li>
					<img src= {% static "products/imagenes/candado.png" %}>
					<h3>Plataforma de pago seguro</h3>
				</li>
			</ul>
		</div>
	</footer>

</body>
</html>

ecommerce/products/templates/products/category_detail.html
{% extends 'products/base.html' %}
{% load static %}
{% block title %}Inicio{% endblock %}
{% block header %}
    <header id="registration3">
    <div class="menu">
      <div class="contenedor">
        <div id="introduccion">
          <p class="blanco"><span>Venta Oficial</span> de la marca Saphirus®</p>
          <p class="blanco">Aromatización ambiental</p>
          <p class="blanco">Contamos con toda la linea de productos.</p>
        </div>
        <div id="imagen">
          <a href= "{% url 'mainapp:inicio' %}"><img id="logo-login" src={% static "products/imagenes/logo.jpeg" %}></a>
        </div>
        <div>
          <img id="saphirus" src= {% static 'products/imagenes/saphirus.jpeg' %}>
        </div>
      </div>
    </div>

  {% block content %}
    <div class="container">
      	<h2 class="blanco catalogo">Catálogo 2020</h2>
        <table class="table table-bordered">
          <thead>
            <tr>
              <td>Producto</td>
              <td>Precio</td>
              <td>Agregar</td>
            </tr>
          </thead>
          <tbody>
          {% for prod in products %}
          <tr>
              <td>
                <span> {{ prod.name }} </span>
              </td>
          	  <td>
                <span class="price-new">${{prod.price}}</span>
              </td>
              <td>
                <a href="{% url 'mainapp:cart' prod.slug %}" class="text-uppercase"><i class="fas fa-shopping-cart" id="negro"></i>
                <span>Agregar al pedido</span></a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
    </div>
</div>
 </div>
{% endblock %}
</header>
  {% endblock %}
  {% block footer %}

    <footer>
    <div class="contenedor">
      <ul>
        <li>
          <img class="login-img" src= {% static "products/imagenes/user.png" %}>
          <h3 class="login">Atención Personalizada</h3>
        </li>
        <li>
          <img class="login-img" src= {% static "products/imagenes/carrito.png" %}>
          <h3 class="login">Pedidos Online</h3>
        </li>
        <li>
          <img class="login-img" id="ubicacion" src= {% static "products/imagenes/map.png" %}>
          <h3 class="login">Envíos a todo el país</h3>
        </li>
        <li>
          <img class="login-img" src= {% static "products/imagenes/candado.png" %}>
          <h3 class="login">Plataforma de pago seguro</h3>
        </li>
      </ul>
    </div>
  </footer>

  {% endblock %}

ecommerce/products/templates/products/home.html
{% extends 'products/base.html' %}
{% load static %}
{% block title %}Inicio{% endblock %}
{% block header %}
    <header id="categorias">
    <div class="menu">
      <div class="contenedor">
        <div id="introduccion">
          <p class="blanco"><span>Venta Oficial</span> de la marca Saphirus®</p>
          <p class="blanco">Aromatización ambiental</p>
          <p class="blanco">Contamos con toda la linea de productos.</p>
        </div>
        <div id="imagen">
          <a href= "{% url 'mainapp:inicio' %}"><img id="logo-login" src={% static "products/imagenes/logo.jpeg" %}></a>
        </div>
        <div>
          <img id="saphirus" src= {% static 'products/imagenes/saphirus.jpeg' %}>
        </div>
      </div>
    </div>

  {% block content %}
  <div class="categorias">
    <div class="contenedor-categorias">
      <ul>
        {% for cat in object_list %}
        <li> <a href='{% url 'mainapp:category_details' pk=cat.pk %}'>{{ cat.title }}</a></li>
        {% endfor %}
      </ul>
    </div>
    <div class="imagenes-categoria">
      <img id="saphirus3" src= {% static 'products/imagenes/saphirus.png' %}>
    </div>
  </div>


  {% endblock %}
  </header>
  {% endblock %}
  {% block footer %}

    <footer>
    <div class="contenedor">
      <ul>
        <li>
          <img class="login-img" src= {% static "products/imagenes/user.png" %}>
          <h3 class="login">Atención Personalizada</h3>
        </li>
        <li>
          <img class="login-img" src= {% static "products/imagenes/carrito.png" %}>
          <h3 class="login">Pedidos Online</h3>
        </li>
        <li>
          <img class="login-img" id="ubicacion" src= {% static "products/imagenes/map.png" %}>
          <h3 class="login">Envíos a todo el país</h3>
        </li>
        <li>
          <img class="login-img" src= {% static "products/imagenes/candado.png" %}>
          <h3 class="login">Plataforma de pago seguro</h3>
        </li>
      </ul>
    </div>
  </footer>

  {% endblock %}