ecommerce/checkout/urls.py
from django.urls import path 
from . views import checkout,charge, oderView, OrderList, CartView

app_name = "checkout"

urlpatterns = [
	path('checkout/', checkout, name="index"),
	path('charge/', charge, name="charge"),
	path('my-orders/', oderView, name="oderView"),
	path('listado_pedido', OrderList.as_view(), name="orderlist"),
	path('pedido/<username>',CartView, name='order_listar'),    
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
 	path('', include('products.urls')),
 	path('', include('checkout.urls',)),
    path('admin/', admin.site.urls),
    path('accounts/', include('registration.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/products/urls.py
from django.urls import path, re_path
from cart.views import add_to_cart, remove_from_cart, CartView, decreaseCart
from .views import Home, home1,  ProductDetail, Productos, SingleCat

app_name="mainapp"
urlpatterns = [
    path('inicio', Home.as_view(), name='home'),
    path('', home1, name='inicio'),
    path('product/<slug>/', ProductDetail.as_view(), name='product'),
    path('cart/', CartView, name='cart-home'),
    path('cart/<slug>', add_to_cart, name='cart'),
    path('decrease-cart/<slug>', decreaseCart, name='decrease-cart'),
    path('remove/<slug>', remove_from_cart, name='remove-cart'),
    re_path(r'^(?P<pk>\d+)$', SingleCat.as_view(), name='category_details'),
]	

ecommerce/checkout/models.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth import get_user_model
# Create your models here.

# Get the user model
User = get_user_model()

class BillingAddress(models.Model):

	user = models.ForeignKey(User, on_delete=models.CASCADE)
	address = models.CharField(max_length=100)
	zipcode = models.CharField(max_length=50)
	city = models.CharField(max_length=30)
	landmark = models.CharField(max_length=20)

	def __str__(self):
		return f'{self.user.username} billing address'

	class Meta:
		verbose_name_plural = "Billing Addresses"


# Address Form
class BillingForm(ModelForm):

	class Meta:
		model = BillingAddress
		fields = ['address', 'zipcode', 'city', 'landmark']

ecommerce/checkout/views.py
import uuid
from django.utils.crypto import get_random_string
from django.conf import settings
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from cart.models import Order, Cart
from . models import BillingForm, BillingAddress
from django.views.generic.base import TemplateView
from django.http import HttpResponse
from django.views.generic.list import ListView

def checkout(request):	
	
	order_qs = Order.objects.filter(user= request.user, encargado=False)
	order_items = order_qs[0].orderitems.all()
	order_total = order_qs[0].get_totals() 
	context = {"order_items": order_items, "order_total": order_total}				
	return render(request, 'checkout/index.html', context)


def charge(request):
	return render (request, 'checkout/charge.html')



def oderView(request):

	try:
		orders = Order.objects.filter(encargado=False)
		context = {
			"orders": orders
		}
	except:
		messages.warning(request, "No hay pedidos realizados")
		return redirect('/')
	return render(request, 'checkout/order.html', context)

class OrderList(ListView):
	model = Order
	template_name = 'checkout/order_list.html'
	queryset = model.objects.filter(encargado=False)

def OrderDetail(request, username):
    order = get_object_or_404(Order, user__username=username)
    context = {'order': order}
    return render(request, 'checkout/order_detail.html' , context )


def CartView(request, username):

    carts = Cart.objects.filter(user__username=username, purchased=False)
    orders = Order.objects.filter(user__username=username, encargado=False)

    if carts.exists():
        if orders.exists():
            order = orders[0]
            return render(request, 'checkout/order_detail.html', {"carts": carts, "order": order})
        else:
            messages.warning(request, "No tienes productos agregados en tu pedido")
            return redirect("mainapp:home")
		
    else:
        messages.warning(request, "No tienes productos agregados en tu pedido")
        return redirect("mainapp:home")

ecommerce/checkout/templates/checkout/charge.html
{% extends 'products/base.html' %}
{% load static %}
{% block title %}Inicio{% endblock %}
{% block header %}

<header class="final2">
    <div class="menu">
      <div class="contenedor">
        <div id="introduccion">
          <p class="blanco"><span>Venta Oficial</span> de la marca Saphirus®</p>
          <p class="blanco">Aromatización ambiental</p>
          <p class="blanco">Contamos con toda la linea de productos.</p>
        </div>
        <div id="imagen">
          <a href= "{% url 'mainapp:inicio' %}"><img id="logo-login" src={% static "products/imagenes/logo.jpeg" %}></a>
        </div>
        <div>
          <img id="saphirus" src= {% static 'products/imagenes/saphirus.jpeg' %}>
        </div>
      </div>
    </div>

{% block content %}

	<div class="contenedor">
		<div class="final">
			<h2 class="text-center blanco">Muchas gracias por su pedido.</h2>
			<a href= "{% url 'mainapp:home' %}" class="btn btn-success inicio">Inicio</a>
		</div>
	</div>

{% endblock %}

</header>
  {% endblock %}
  {% block footer %}

    <footer id="final">
    <div class="contenedor">
      <ul>
        <li>
          <img class="login-img" src= {% static "products/imagenes/user.png" %}>
          <h3 class="login">Atención Personalizada</h3>
        </li>
        <li>
          <img class="login-img" src= {% static "products/imagenes/carrito.png" %}>
          <h3 class="login">Pedidos Online</h3>
        </li>
        <li>
          <img class="login-img" id="ubicacion" src= {% static "products/imagenes/map.png" %}>
          <h3 class="login">Envíos a todo el país</h3>
        </li>
        <li>
          <img class="login-img" src= {% static "products/imagenes/candado.png" %}>
          <h3 class="login">Plataforma de pago seguro</h3>
        </li>
      </ul>
    </div>
  </footer>

  {% endblock %}

ecommerce/checkout/templates/checkout/index.html
{% extends 'products/base.html' %}
{% load static %}
{% block title %}Inicio{% endblock %}
{% block header %}

<header id="categorias">
    <div class="menu">
      <div class="contenedor">
        <div id="introduccion">
          <p class="blanco"><span>Venta Oficial</span> de la marca Saphirus®</p>
          <p class="blanco">Aromatización ambiental</p>
          <p class="blanco">Contamos con toda la linea de productos.</p>
        </div>
        <div id="imagen">
          <a href= "{% url 'mainapp:inicio' %}"><img id="logo-login" src={% static "products/imagenes/logo.jpeg" %}></a>
        </div>
        <div>
          <img id="saphirus" src= {% static 'products/imagenes/saphirus.jpeg' %}>
        </div>
      </div>
    </div>

{% block content %}

<div class="categorias9">
  <div class="contenedor-categorias2">
    <h2 class="blanco detalle2">Detalle de Pedido</h2>
      <ul class="detalle">
      {% for item in order_items %}
      <li>{{ item.item.name }} = {{ item.quantity }}</li>{% endfor %}
    </ul>
    <span class="blanco detalle2" id="total"><b>Total del Pedido: $ {{ order_total | floatformat:2 }}</b></span>
    <a href="{% url 'checkout:charge' %}" class="btn btn-primary float-right" id="confirmar">Confirmar Pedido</a>
  </div>
</div>
{% endblock %}
</header>
  {% endblock %}
  {% block footer %}

    <footer>
    <div class="contenedor">
      <ul>
        <li>
          <img class="login-img" src= {% static "products/imagenes/user.png" %}>
          <h3 class="login">Atención Personalizada</h3>
        </li>
        <li>
          <img class="login-img" src= {% static "products/imagenes/carrito.png" %}>
          <h3 class="login">Pedidos Online</h3>
        </li>
        <li>
          <img class="login-img" id="ubicacion" src= {% static "products/imagenes/map.png" %}>
          <h3 class="login">Envíos a todo el país</h3>
        </li>
        <li>
          <img class="login-img" src= {% static "products/imagenes/candado.png" %}>
          <h3 class="login">Plataforma de pago seguro</h3>
        </li>
      </ul>
    </div>
  </footer>

  {% endblock %}

ecommerce/checkout/templates/checkout/order.html
{% extends 'products/base.html' %}
{% block content %}

<div class="container mt-5">
<h2 class="text-center"><strong>Listado de Pedidos</strong></h2>
<div class="row">
	<div class="col-md-12">
		<div class="card mt-5" style="height: auto">
			<div class="table-responsive">
			<table class="table">
			  <thead>
			    <tr>			      
			      <th scope="col">Número de Pedido</th>
			      <th scope="col">Usuario</th>
			      <th scope="col">Estado</th>
			    </tr>
			  </thead>
			  <tbody>
			    
			    
			    {% for order in object_list %}
			    <tr>
			      <th scope="row">{{ forloop.counter }}</th>
			      <td>{{ order.user }}</td>
			      <td><a href="{% url 'checkout:index' order.id %}">Ver Pedido</a></td>
			    </tr>
			      {% endfor %}
			    
			  </tbody>
			</table>
			</div>
		</div>
	</div>
	<div class="col-md-12 my-5 text-center">
		<a href="/" class="btn btn-success">INICIO</a>
	</div>
</div>
</div>

{% endblock %}

ecommerce/checkout/templates/checkout/order_detail.html
{% extends 'products/base.html' %}
{% load static %}
{% block title %}Inicio{% endblock %}
{% block header %}
    <header id="carrito">
    <div class="menu">
      <div class="contenedor">
        <div id="introduccion">
          <p class="blanco"><span>Venta Oficial</span> de la marca Saphirus®</p>
          <p class="blanco">Aromatización ambiental</p>
          <p class="blanco">Contamos con toda la linea de productos.</p>
        </div>
        <div id="imagen">
          <a href= "{% url 'mainapp:inicio' %}"><img id="logo-login" src={% static "products/imagenes/logo.jpeg" %}></a>
        </div>
        <div>
          <img id="saphirus" src= {% static 'products/imagenes/saphirus.jpeg' %}>
        </div>
      </div>
    </div>

{% block content %}
<div class="container">
<div>
	<h2 class="blanco catalogo">Detalle</h2>
</div >
<table class="table-responsive">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Producto</th>
      <th scope="col">Cant.</th>
      <th scope="col">Monto</th>
    </tr>
  </thead>
  <tbody>
  	{% for cart in carts %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ cart.item.name }}</td>
      <td>
        <span>{{ cart.quantity }}</span>
      </td>
      <td>${{ cart.get_total }}</td>
    </tr>
	{% endfor %}
    <tr>
      <th scope="row"></th>
      <td colspan="2">Total</td>
      <td>${{ order.get_totals| floatformat:2 }}</td>
    </tr>
  </tbody>
</table>
</div>

{% endblock %}
</header>
{% endblock %}
{% block footer %}

  <footer id="footercarrito">
  <div class="contenedor">
    <ul>
      <li>
        <img class="login-img" src= {% static "products/imagenes/user.png" %}>
        <h3 class="login">Atención Personalizada</h3>
      </li>
      <li>
        <img class="login-img" src= {% static "products/imagenes/carrito.png" %}>
        <h3 class="login">Pedidos Online</h3>
      </li>
      <li>
        <img class="login-img" id="ubicacion" src= {% static "products/imagenes/map.png" %}>
        <h3 class="login">Envíos a todo el país</h3>
      </li>
      <li>
        <img class="login-img" src= {% static "products/imagenes/candado.png" %}>
        <h3 class="login">Plataforma de pago seguro</h3>
      </li>
    </ul>
  </div>
</footer>

{% endblock %}

ecommerce/checkout/templates/checkout/order_list.html
{% extends 'products/base.html' %}
{% load static %}
{% block title %}Inicio{% endblock %}
{% block header %}
    <header id="carrito">
    <div class="menu">
      <div class="contenedor">
        <div id="introduccion">
          <p class="blanco"><span>Venta Oficial</span> de la marca Saphirus®</p>
          <p class="blanco">Aromatización ambiental</p>
          <p class="blanco">Contamos con toda la linea de productos.</p>
        </div>
        <div id="imagen">
          <a href= "{% url 'mainapp:inicio' %}"><img id="logo-login" src={% static "products/imagenes/logo.jpeg" %}></a>
        </div>
        <div>
          <img id="saphirus" src= {% static 'products/imagenes/saphirus.jpeg' %}>
        </div>
      </div>
    </div>
{% block content %}

<div class="container mt-5">
<h2 class="text-center blanco"><strong>Listado de Pedidos</strong></h2>
<div class="row">
	<div class="col-md-12">
		<div class="card mt-5" style="height: auto">
			<div class="table-responsive">
			<table class="table">
			  <thead>
			    <tr>
			      <th scope="col">Pedido</th>
			      <th scope="col">Usuario</th>
			      <th scope="col">Estado</th>
			    </tr>
			  </thead>
			  <tbody>


			    {% for order in object_list %}
			    <tr>
			      <th scope="row">{{ forloop.counter }}</th>
			      <td>{{ order.user }}</td>
			      <td><a href="{% url 'checkout:order_listar' order.user %}">Ver Pedido</a></td>
			    </tr>
			      {% endfor %}

			  </tbody>
			</table>
			</div>
		</div>
	</div>
	<div class="col-md-12 my-5 text-center">
		<a href="/" class="btn btn-success">INICIO</a>
	</div>
</div>
</div>

{% endblock %}
</header>
{% endblock %}
{% block footer %}

  <footer id="footercarrito">
  <div class="contenedor">
    <ul>
      <li>
        <img class="login-img" src= {% static "products/imagenes/user.png" %}>
        <h3 class="login">Atención Personalizada</h3>
      </li>
      <li>
        <img class="login-img" src= {% static "products/imagenes/carrito.png" %}>
        <h3 class="login">Pedidos Online</h3>
      </li>
      <li>
        <img class="login-img" id="ubicacion" src= {% static "products/imagenes/map.png" %}>
        <h3 class="login">Envíos a todo el país</h3>
      </li>
      <li>
        <img class="login-img" src= {% static "products/imagenes/candado.png" %}>
        <h3 class="login">Plataforma de pago seguro</h3>
      </li>
    </ul>
  </div>
</footer>

{% endblock %}